### ISSUE TITLE
Word break logic in request cards looks a bit arbitrary

### ISSUE THREAD

**Issue by larxn** [veganhacktivists/veganhacktivists#121]
## Problem
The word break logic in request cards looks a bit arbitrary. I thought it was just my habit of reading in Spanish, but there are some similar conventions in English [¹](https://grammar.collinsdictionary.com/easy-learning/when-do-you-use-a-hyphen-in-english) [²](https://english.stackexchange.com/questions/385/what-are-the-rules-for-splitting-words-at-the-end-of-a-line) [³](http://www.butte.edu/departments/cas/tipsheets/punctuation/hyphen.html).

I think the default [`word-break`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) value would work just fine (and it's also what sites like [The Guardian](https://www.theguardian.com/commentisfree/2019/aug/08/ipcc-land-climate-report-carbon-cost-meat-dairy), [The New Yorker](https://www.newyorker.com/culture/the-new-yorker-interview/the-underground-worlds-of-haruki-murakami), or the [BBC](https://www.bbc.com/culture/article/20220831-white-noise-is-thrillingly-original)  use). Or is there a reason why you needed to use `break-all`? Maybe I could help.

## Screenshot
![image](https://user-images.githubusercontent.com/16514302/188025223-7092c6ea-03d4-4762-a06f-429db2ab4f3d.png)

**Comment by JoaquinTrinanes** [comment]
Thanks for the report! I'm about to merge a fix changing `break-all` to `break-word`. The reason I used the former one was because without specifying anything long URLs (or long strings without spaces in general) looked like this:
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/1385934/188232042-92d8cf6d-0e2d-4436-bc29-12a1d9c80e59.png">

I (incorrectly) assumed that `break-word` would have the same behaviour, but it doesn't! 😁
